### ISSUE TITLE
crash app on resume

### ISSUE THREAD

**Issue by mbf5923** [Cleveroad/LoopBar#13]
hi
when i resume app, using loopbar app crash:

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rahasoft.njf.najafabad/com.rahasoft.njf.najafabad.NewsActivity}: java.lang.RuntimeException: bad array lengths
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
	at android.app.ActivityThread.access$800(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5317)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.RuntimeException: bad array lengths
	at android.os.Parcel.readBooleanArray(Parcel.java:811)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState.<init>(LoopBarView.java:907)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState.<init>(LoopBarView.java:0)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState$1.createFromParcel(LoopBarView.java:876)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState$1.createFromParcel(LoopBarView.java:873)
	at android.os.Parcel.readParcelable(Parcel.java:2277)
	at android.os.Parcel.readValue(Parcel.java:2177)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2571)
	at android.os.Parcel.readSparseArray(Parcel.java:1899)
	at android.os.Parcel.readValue(Parcel.java:2234)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2510)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1983)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1022)
	at android.app.Activity.performRestoreInstanceState(Activity.java:977)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
	... 10 more
java.lang.RuntimeException: bad array lengths
	at android.os.Parcel.readBooleanArray(Parcel.java:811)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState.<init>(LoopBarView.java:907)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState.<init>(LoopBarView.java:0)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState$1.createFromParcel(LoopBarView.java:876)
	at com.cleveroad.loopbar.widget.LoopBarView$SavedState$1.createFromParcel(LoopBarView.java:873)
	at android.os.Parcel.readParcelable(Parcel.java:2277)
	at android.os.Parcel.readValue(Parcel.java:2177)
	at android.os.Parcel.readSparseArrayInternal(Parcel.java:2571)
	at android.os.Parcel.readSparseArray(Parcel.java:1899)
	at android.os.Parcel.readValue(Parcel.java:2234)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:2510)
	at android.os.BaseBundle.unparcel(BaseBundle.java:221)
	at android.os.Bundle.getSparseParcelableArray(Bundle.java:871)
	at com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.java:1983)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1022)
	at android.app.Activity.performRestoreInstanceState(Activity.java:977)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1161)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2318)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2405)
	at android.app.ActivityThread.access$800(ActivityThread.java:149)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5317)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by ValeryGes** [comment]
Hi @mbf5923, could you attach your xml and java code?

**Comment by ValeryGes** [comment]
@mbf5923, also try version 1.1.3, it contains several fixes with state saving process
