### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed

### ISSUE THREAD

**Issue by death14stroke** [Cleveroad/LoopBar#30]
I am using Loopbar with target SDK 29 and min 21 running on an Android SDK 28 device. I get the following error when added loop bar in Activity:

`java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipRect(Canvas.java:826)
        at com.cleveroad.loopbar.widget.NegativeMarginFixColorDrawable.draw(NegativeMarginFixColorDrawable.java:14)
        at android.view.View.getDrawableRenderNode(View.java:22206)
        at android.view.View.drawBackground(View.java:22112)
        at android.view.View.draw(View.java:21868)
        at android.view.View.updateDisplayListIfDirty(View.java:20750)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21880)
        at android.view.View.updateDisplayListIfDirty(View.java:20750)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21880)
        at android.view.View.updateDisplayListIfDirty(View.java:20750)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21880)
        at android.view.View.updateDisplayListIfDirty(View.java:20750)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1765)
        at android.view.View.updateDisplayListIfDirty(View.java:20736)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20736)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20736)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20736)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.updateDisplayListIfDirty(View.java:20736)
        at android.view.View.draw(View.java:21603)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4558)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4333)
        at android.view.View.draw(View.java:21880)
        at com.android.internal.policy.DecorView.draw(DecorView.java:1120)
        at android.view.View.updateDisplayListIfDirty(View.java:20750)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:725)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:731)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:840)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4006)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3770)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3079)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1942)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8595)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
        at android.view.Choreographer.doCallbacks(Choreographer.java:765)
        at android.view.Choreographer.doFrame(Choreographer.java:700)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)`

**Comment by VadimHalimendikCr** [comment]
Hi, @Death14Stroke ,

Thank you for your question and for using our library.
This error is related to the SDK version. We updated the version of the SDK and fixed the bug.
You can connect the new version by reference: implementation "com.cleveroad:loopbar:1.2.0"
